import type { Metadata } from 'next';
import { getFonts } from '@/src/app/fonts';
import { clsx } from 'clsx';
import './globals.css';
import { Provider } from '@/src/app/provider';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={clsx(getFonts())}>
				{/* <Provider> */}
					{children}
				{/* </Provider> */}
			</body>
		</html>
	);
}
